#!/usr/bin/env python3
"""Import an arcbench task folder into this grader repo as a single command.

    python3 scripts/import_task.py /path/to/arcbench/task --task-id my-task

Reads the arcbench task's own requirements.yaml (whatever shape it's in —
nested, differently-named fields) and writes this grader's flat
tasks/<task_id>/requirements/requirements.yaml, deriving sane defaults for
anything the arcbench file doesn't specify. Copies requirements.md,
reference/, assets/ and tests/*.spec.ts across unchanged. Stages the result
with `git add` (never commits/pushes — review the diff yourself, especially
`visibility`, before pushing).

SAFETY: refuses to run against a working tree whose git remote looks like
the public arcbench-selftest-demo repo. Real task content (this script's
whole purpose) must only ever land in a private grader repo.
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

try:
    import yaml  # PyYAML — not in the stdlib, install from PyPI if missing.
except ImportError:
    print(
        "error: this script needs PyYAML to read arbitrary arcbench "
        "requirements.yaml shapes.\n  pip install pyyaml",
        file=sys.stderr,
    )
    sys.exit(2)

DEFAULTS = {
    "app_port": 3000,
    "build_timeout_s": 600,
    "ready_timeout_s": 60,
    "run_timeout_s": 900,
}
PUBLIC_REPO_MARKER = "arcbench-selftest-demo"


def find_repo_root(start: Path) -> Path:
    cur = start.resolve()
    for p in [cur, *cur.parents]:
        if (p / ".git").exists():
            return p
    print(f"error: {start} is not inside a git repo (no .git found)", file=sys.stderr)
    sys.exit(2)


def guard_not_public_repo(repo_root: Path) -> None:
    try:
        out = subprocess.run(
            ["git", "-C", str(repo_root), "remote", "get-url", "origin"],
            capture_output=True, text=True, check=False,
        ).stdout.strip()
    except OSError:
        out = ""
    if PUBLIC_REPO_MARKER in out:
        print(
            f"error: refusing to import real task content into a repo whose "
            f"origin looks like the PUBLIC demo repo ({out!r}). Real tasks "
            f"only go in a private grader repo.",
            file=sys.stderr,
        )
        sys.exit(2)


def dig(d: dict, *path, default=None):
    cur = d
    for key in path:
        if not isinstance(cur, dict) or key not in cur:
            return default
        cur = cur[key]
    return cur


def load_arcbench_requirements(src: Path) -> dict:
    req_path = src / "requirements" / "requirements.yaml"
    if not req_path.is_file():
        print(f"error: no requirements/requirements.yaml under {src}", file=sys.stderr)
        sys.exit(2)
    with open(req_path) as f:
        data = yaml.safe_load(f) or {}
    if not isinstance(data, dict):
        print(f"error: {req_path} did not parse to a mapping", file=sys.stderr)
        sys.exit(2)
    return data


def derive_fields(data: dict, task_id_hint: str) -> dict:
    task_id = data.get("task_id") or data.get("id") or task_id_hint
    title = data.get("title") or data.get("name") or task_id
    visibility = data.get("visibility")  # may be absent; caller's --visibility wins if given
    app_port = (
        data.get("app_port")
        or dig(data, "app", "port")
        or dig(data, "web", "port")
        or DEFAULTS["app_port"]
    )
    build_timeout_s = (
        data.get("build_timeout_s")
        or dig(data, "limits", "build_timeout_s")
        or dig(data, "timeouts", "build_s")
        or DEFAULTS["build_timeout_s"]
    )
    ready_timeout_s = (
        data.get("ready_timeout_s")
        or dig(data, "limits", "ready_timeout_s")
        or dig(data, "timeouts", "ready_s")
        or DEFAULTS["ready_timeout_s"]
    )
    run_timeout_s = (
        data.get("run_timeout_s")
        or dig(data, "limits", "run_timeout_s")
        or dig(data, "timeouts", "run_s")
        or DEFAULTS["run_timeout_s"]
    )
    return {
        "task_id": str(task_id),
        "title": str(title),
        "visibility": visibility,
        "app_port": int(app_port),
        "build_timeout_s": int(build_timeout_s),
        "ready_timeout_s": int(ready_timeout_s),
        "run_timeout_s": int(run_timeout_s),
    }


def write_flat_requirements(dest: Path, fields: dict, source_file: Path) -> None:
    lines = [
        "# Auto-generated by scripts/import_task.py from",
        f"# {source_file} — flat key: value on purpose, see that script for why.",
        f"task_id: {fields['task_id']}",
        f"title: {fields['title']}",
        f"visibility: {fields['visibility']}",
        f"app_port: {fields['app_port']}",
        f"build_timeout_s: {fields['build_timeout_s']}",
        f"ready_timeout_s: {fields['ready_timeout_s']}",
        f"run_timeout_s: {fields['run_timeout_s']}",
        "",
    ]
    dest.write_text("\n".join(lines))


def copy_tree_if_present(src: Path, dest: Path) -> bool:
    if not src.exists():
        return False
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(src, dest)
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("source", type=Path, help="arcbench task folder (contains requirements/ and tests/)")
    ap.add_argument("--task-id", help="override the task id (default: from source's requirements.yaml, or the folder name)")
    ap.add_argument("--visibility", choices=["public", "hidden"], help="override visibility (required if the arcbench requirements.yaml doesn't set one)")
    ap.add_argument("--dest-repo", type=Path, default=Path.cwd(), help="grader repo root (default: current directory)")
    ap.add_argument("--force", action="store_true", help="overwrite an existing tasks/<task_id> folder")
    args = ap.parse_args()

    src = args.source.resolve()
    if not src.is_dir():
        print(f"error: {src} is not a directory", file=sys.stderr)
        return 2

    repo_root = find_repo_root(args.dest_repo)
    guard_not_public_repo(repo_root)

    arcbench_req = load_arcbench_requirements(src)
    fields = derive_fields(arcbench_req, task_id_hint=args.task_id or src.name)
    if args.task_id:
        fields["task_id"] = args.task_id
    if args.visibility:
        fields["visibility"] = args.visibility
    if not fields["visibility"]:
        print(
            "error: no visibility in the source requirements.yaml and none given — "
            "pass --visibility public|hidden",
            file=sys.stderr,
        )
        return 2

    task_dir = repo_root / "tasks" / fields["task_id"]
    if task_dir.exists() and not args.force:
        print(f"error: {task_dir} already exists (use --force to overwrite)", file=sys.stderr)
        return 2

    tests_src = src / "tests"
    if not tests_src.is_dir() or not list(tests_src.glob("*.spec.ts")):
        print(f"error: no tests/*.spec.ts under {src}", file=sys.stderr)
        return 2

    (task_dir / "requirements").mkdir(parents=True, exist_ok=True)
    write_flat_requirements(task_dir / "requirements" / "requirements.yaml", fields, src / "requirements" / "requirements.yaml")

    md_src = src / "requirements" / "requirements.md"
    if md_src.is_file():
        shutil.copy2(md_src, task_dir / "requirements" / "requirements.md")

    copy_tree_if_present(src / "requirements" / "reference", task_dir / "requirements" / "reference")
    copy_tree_if_present(src / "requirements" / "assets", task_dir / "requirements" / "assets")
    copy_tree_if_present(tests_src, task_dir / "tests")

    subprocess.run(["git", "-C", str(repo_root), "add", str(task_dir.relative_to(repo_root))], check=True)

    print(f"imported {src} -> {task_dir}")
    print(f"  task_id={fields['task_id']} visibility={fields['visibility']} "
          f"app_port={fields['app_port']} timeouts(build/ready/run)="
          f"{fields['build_timeout_s']}/{fields['ready_timeout_s']}/{fields['run_timeout_s']}")
    print("Review the diff (especially visibility, timeouts), then:")
    print(f'  git -C "{repo_root}" commit -m "Import task {fields["task_id"]}" && '
          f'git -C "{repo_root}" push')
    return 0


if __name__ == "__main__":
    sys.exit(main())
